### ISSUE TITLE
Endpoint /api returns 404 behind Traefik on k3s

### ISSUE THREAD

**Issue by gianmarco-mameli** [portainer/k8s#146]
Hi, I'm deploying Portainer on a 3 node k3s cluster, ARM64, behind a traefik 3 reverse proxy.
All installation went fine but portainer UI remain stuck on 'Loading Portainer', also I have the message 'Failure
Unable to retrieve server settings and status' and if I check on the browser console I see that the gets to '/api' returns 404.
This is my traefik ingressroute configuration, I need to use only http because I have a balancer in front of the nodes
```yaml
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: portainer-dashboard
  namespace: portainer
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`portainer.domain`)
       kind: Rule
       services:
          - name: portainer
            port: 9000
```
I also tryed adding ' && PathPrefix(\`/\`) || PathPrefix(\`/api\`)' to the match
Any clues?
Thanks
