### ISSUE TITLE
Portainer on GKE - Errors querying Portainer API

### ISSUE THREAD

**Issue by cristian04** [portainer/k8s#22]
I am receiving several errors with my Portainer instance. I've followed the instructions available on https://www.portainer.io/installation/ 

I am using Helm 3 on K8S  v1.17.9-gke.1504  The service is exposed using Ingress. 

This happens when I browse https://portainer.demos.clvr.cloud/#!/1/kubernetes/dashboard

![image](https://user-images.githubusercontent.com/521587/96118824-8ea25f80-0f48-11eb-888c-24dfe2f2bd1c.png)

```
❯ helm list  -n portainer
NAME     	NAMESPACE	REVISION	UPDATED                              	STATUS  	CHART          	APP VERSION
portainer	portainer	2       	2020-10-16 00:17:57.040719 +1300 NZDT	deployed	portainer-1.0.3	2.0.0
```

Values file
```
image:
  pullPolicy: IfNotPresent
  repository: portainer/portainer-ce
  tag: latest
imagePullSecrets: []
ingress:
  annotations:
    certmanager.k8s.io/acme-challenge-type: http01
    certmanager.k8s.io/cluster-issuer: xxxxx
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/auth-signin: xxxxxxxxxxxxxx
    nginx.ingress.kubernetes.io/auth-url: xxxxxxxxxxx
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  enabled: true
  hosts:
  - host: xxxxxxxxxx
    paths:
    - path: /
      port: 9000
  tls:
  - hosts:
    - xxxxxxxxxxxx
    secretName: xxxxxxxxx-tls
persistence:
  annotations: {}
  size: 10Gi
replicaCount: 1
resources: {}
service:
  annotations: {}
  edgeNodePort: 30776
  edgePort: 8000
  httpNodePort: 30777
  httpPort: 9000
  type: ClusterIP
serviceAccount:
  annotations: {}
  name: portainer-sa-clusteradmin
```

Portainer Pod Log:
```
2020-10-15T11:21:38.314989155Z 2020/10/15 11:21:38 server: Reverse tunnelling enabled
2020-10-15T11:21:38.315053807Z 2020/10/15 11:21:38 server: Fingerprint 23:d5:ac:6e:2d:bd:65:0b:5e:45:24:5b:ee:6f:36:06
2020-10-15T11:21:38.315066086Z 2020/10/15 11:21:38 server: Listening on 0.0.0.0:8000...
2020-10-15T11:21:38.319101178Z 2020/10/15 11:21:38 Starting Portainer 2.0.0 on :9000
2020-10-15T11:21:38.319580475Z 2020/10/15 11:21:38 [DEBUG] [chisel, monitoring] [check_interval_seconds: 10.000000] [message: starting tunnel management process]
2020-10-15T11:21:53.802212793Z 2020/10/15 11:21:53 http error: Invalid JWT token (err=Invalid JWT token) (code=401)
```

Google Chrome DevTools Network:
```
GET https://portainer.demos.clvr.cloud/api/settings
401
{"message":"Invalid JWT token","details":"Invalid JWT token"}
[...]
Some Queries to /namespaces /tags and /status. No issues
[...]
GET https://portainer.demos.clvr.cloud/api/endpoints/1/kubernetes/api/v1/namespaces/adm/resourcequotas/portainer-rq-adm
404
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "resourcequotas \"portainer-rq-cert-manager\" not found",
  "reason": "NotFound",
  "details": {
    "name": "portainer-rq-cert-manager",
    "kind": "resourcequotas"
  },
  "code": 404
}
[..]
```
