### ISSUE TITLE
Issue with PVC not ready

### ISSUE THREAD

**Issue by MarkLFT** [portainer/k8s#59]
I am trying to install portainer into a kubernetes cluster, using the instructions found on your website.  But when I install the helm chart, the portainer pod remains in a Creating state. 

If I use describe on the pod I get....
Events:
  Type     Reason            Age                    From               Message
  ----     ------            ----                   ----               -------
  Warning  FailedScheduling  3m39s (x3 over 3m43s)  default-scheduler  0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims.
  Normal   Scheduled         3m34s                  default-scheduler  Successfully assigned portainer/portainer-7b6c599757-9jltq to k8snode0
  Warning  FailedMount       94s                    kubelet            MountVolume.MountDevice failed for volume "pvc-4c67a455-953e-439d-a8a2-049937d24b27" : rpc error: code = DeadlineExceeded desc = context deadline exceeded
  Warning  FailedMount       94s                    kubelet            MountVolume.MountDevice failed for volume "pvc-4c67a455-953e-439d-a8a2-049937d24b27" : rpc error: code = Aborted desc = operation locked due to in progress operation(s): ["volume_id_pvc-4c67a455-953e-439d-a8a2-049937d24b27"]
  Warning  FailedMount       91s                    kubelet            Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[data kube-api-access-c78bm]: timed out waiting for the condition

I have checked on the NAS, the volume has been created.  But you container seems to have an issue using it.

Here are my values yaml contents.

`service: 
  type: ClusterIP
ingress:
  enabled: true
  certManager: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: "portainer.*********.com"
      paths:
        - path: /
  tls:
    - hosts:
      - portainer.*********.com
      secretName: portainer-tls
persistence:
  size: "10Gi"
  storageclass: "freenas-iscsi-csi"`

**Comment by funkypenguin** [comment]
Hey @MarkLFT!

At first glance, this looks to be an issue with the mounting of the freenas iSCSI volume... are you able to mount _other_ pods with PVCs using the same storageclass?

Here's a quick set of manifests I often use to test simple pod-pvc issues:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-test
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: freenas-iscsi-csi
---
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: pvc-test
```
