### ISSUE TITLE
Problem with hosts and tls in Helm chart

### ISSUE THREAD

**Issue by Evantage-WS** [portainer/k8s#79]
Hi,

I do have the following helm command:

```
NAMESPACE=portainer
DOMAIN=test.com

helm upgrade portainer -n ${NAMESPACE} portainer/portainer \
    --install \
    --create-namespace \
    --set service.type=ClusterIP \
    --set ingress.enabled=true \
    --set ingress.annotations."kubernetes\.io/ingress\.class"=nginx \
    --set ingress.annotations."cert-manager\.io/cluster-issuer"=letsencrypt-staging \
    --set ingress.hosts.host=portainer.${DOMAIN} \
    --set ingress.tls[0].secretName=portainer.internal.${DOMAIN}-tls \
    --set ingress.tls[0].hosts[0]=portainer.internal.${DOMAIN}
```
but the hosts and tls part are causing problems, I do get this error:
```
coalesce.go:202: warning: destination for hosts is a table. Ignoring non-table value [map[host:<nil> paths:[]]]
Error: template: portainer/templates/ingress.yaml:31:15: executing "portainer/templates/ingress.yaml" at <.host>: can't evaluate field host in type interface {}
```
Can anybody give me a clue what the correct syntax is for the hosts and tls part?

**Comment by pcorbel** [comment]
Hello, you should do

```yaml
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt"
  hosts:
    - host: "portainer.mydomain.com"
      paths: 
        - path: "/"
  tls:
    - hosts:
      - "portainer.mydomain.com"
      secretName: "letsencrypt"
```
